name: XcraftChat
main: de.xcraft.engelier.chat.Chat
version: 0.3
author: Engelier
load: postworld
commands:
  xchat:
    description: Reloads the config
    usage: /<command>
#    permission: XcraftChat.reload
permissions:
  XcraftChat.reload:
    default: OP
    description: allows you to reload the config